import mongoose from "mongoose";
import dbConnect from "@/lib/db/connect";
import Order from "@/lib/db/models/order";
import Product from "@/lib/db/models/product";
import Supplier from "@/lib/db/models/supplier";
import User from "@/lib/db/models/User";
import Customer from "@/lib/db/models/customer";
import { logger } from "@/lib/logger";

const json = (payload, status = 200) =>
  new Response(JSON.stringify(payload), {
    status,
    headers: { "Content-Type": "application/json" },
  });

function safePopulateQuery(query, path, select = "") {
  const registered = mongoose.modelNames();
  function resolveRefForPath(p) {
    const sp = Order.schema.path(p);
    if (!sp) return null;
    if (sp.options && sp.options.ref) return sp.options.ref;
    if (sp.options && sp.options.refPath) return "POLYMORPHIC";
    if (p.includes(".")) {
      const [arrPath, subPath] = p.split(".", 2);
      const arrSchemaPath = Order.schema.path(arrPath);
      if (arrSchemaPath && arrSchemaPath.caster) {
        const casterSchema = arrSchemaPath.caster.schema || arrSchemaPath.caster;
        if (casterSchema && casterSchema.path(subPath) && casterSchema.path(subPath).options) {
           const osp = casterSchema.path(subPath).options;
           if (osp.ref) return osp.ref;
           if (osp.refPath) return "POLYMORPHIC";
        }
      }
    }
    return null;
  }
  const refModel = resolveRefForPath(path);
  if (!refModel) return query;
  if (refModel !== "POLYMORPHIC" && !registered.includes(refModel)) return query;
  return query.populate(path, select);
}

export async function GET(request, { params }) {
  try {
    await dbConnect();
    const { id } = await params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return json({ success: false, error: "Invalid orderId" }, 400);
    }

    let query = Order.findById(id);
    query = safePopulateQuery(query, "user", "name email phone address city state pincode");
    query = safePopulateQuery(query, "supplier", "name");
    query = safePopulateQuery(query, "items.product", "name price sku");

    const order = await query.lean();

    if (!order) {
      return json({ success: false, error: "Order not found" }, 404);
    }

    return json({ success: true, order }, 200);
  } catch (err) {
    console.error("GET /api/order/[id] error:", err);
    return json({ success: false, error: err.message || "Server error" }, 500);
  }
}

export async function PATCH(request, { params }) {
  try {
    await dbConnect();
    const { id } = await params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return json({ success: false, error: "Invalid orderId" }, 400);
    }

    const body = await request.json();
    const order = await Order.findById(id);
    if (!order) {
      return json({ success: false, error: "Order not found" }, 404);
    }

    // Update order status, invoice, payment, or other properties dynamically
    if (body.status) order.status = body.status;
    if (body.invoice) order.invoice = body.invoice;
    if (body.payment) order.payment = body.payment;
    
    // We can also allow dynamic updates of arbitrary fields if sent
    if (body.shippingAddress) order.shippingAddress = body.shippingAddress;
    if (body.delivery) order.delivery = body.delivery;
    if (body.notes) order.notes = body.notes;

    // Use markModified if needed for mixed types
    if (body.invoice) order.markModified("invoice");
    if (body.payment) order.markModified("payment");

    await order.save();

    // INTERCEPT VENDOR INVOICE SUBMISSION: Update PO timeline and fulfillments
    if (body.invoice && body.invoice.invoiceNumber) {
      try {
        const poCollection = mongoose.connection.db.collection("purchaseorders");
        const po = await poCollection.findOne({ poNumber: order.orderNumber });
        
        if (po && po.status !== "Completed") {
          // Check if invoice timeline already exists
          const alreadyLogged = po.timeline?.some(t => t.message?.includes(body.invoice.invoiceNumber));
          
          if (!alreadyLogged) {
            const GoodsReceivedNote = (await import("@/lib/db/models/inventory/GoodsReceivedNote")).default;
            
            const newTimeline1 = {
              status: po.status,
              message: `Invoice #${body.invoice.invoiceNumber} generated by Vendor.`,
              user: "Vendor Portal",
              timestamp: new Date()
            };
            
            // Auto-fulfill: generate GRN for all items
            const grnItems = (po.items || []).map(item => ({
              productId: item.productId,
              productName: item.productName,
              sku: item.sku || "",
              orderedQty: item.quantity || item.orderedQty || Number(item.quantity) || 0,
              receivedQty: item.quantity || item.orderedQty || Number(item.quantity) || 0,
              unitPrice: item.unitPrice || 0,
            }));

            const newGrn = new GoodsReceivedNote({
              purchaseOrderId: po._id,
              poNumber: po.poNumber,
              supplier: po.supplier,
              items: grnItems,
              receivedBy: "Vendor Auto",
              receivedDate: new Date(),
              remarks: `Auto-generated from Vendor Invoice #${body.invoice.invoiceNumber}`,
              status: "Kachha",
              isKachha: true
            });
            await newGrn.save();

            const newTimeline2 = {
              status: "Completed",
              message: `GRN ${newGrn.grnNumber} generated. Status: Completed`,
              user: "System",
              timestamp: new Date()
            };

            await poCollection.updateOne(
              { _id: po._id },
              { 
                $set: { status: "Completed" },
                $push: { timeline: { $each: [newTimeline1, newTimeline2] } }
              }
            );
          }
        }
      } catch (err) {
        console.error("Error auto-fulfilling PO on vendor invoice:", err);
      }
    }

    return json({ success: true, order }, 200);
  } catch (err) {
    console.error("PATCH /api/order/[id] error:", err);
    return json({ success: false, error: err.message || "Server error" }, 500);
  }
}
